theme: minima
title: Hello Guys!!!
author: BigHuang
descreption: I'm a freashman at collegue,my mother-language is Chinese. And i'm najor in Software Engineering.
navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/post/"
  - title: "About"
    url: "/about/" 
posts:
  directory: _posts
  date_format: "2024-12-14"
