theme: minima
title: Hello Guys!!!
author: BigHuang
descreption: I'm a freashman at collegue,my mother-language is Chinese. And i'm najor in Software Engineering.//这里的描述读者是看不见的，例如利用浏览器搜索的时候，可以通过这个描述来进行对应
navbar:
  - title: "Home"
    url: "/index/"
  - title: "Blog"
    url: "/post/"
  - title: "About"
    url: "/about/" 
posts:
  directory: _posts
  date_format: "2024-12-14"
