theme: Minima
title: Hello Guys!!!
author: BigHuang
description: I'm a freshman at college, my mother-language is Chinese. And I'm major in Software Engineering. I love programming, algorithms, and English learning.
baseurl: ""
url: ""
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
navbar:

  - title: "首页"
    url: "/"
  - title: "博客"
    url: "/post/"
  - title: "关于"
    url: "/about/"
    posts:
      directory: _posts
      date_format: "YYYY-MM-DD"
      excerpt_separator: "<!--more-->"
      permalink: /:categories/:title/
    categories:
  - 编程
  - 英语
  - 生活
    tags:
  - C语言
  - C++
  - 编程技巧
  - 算法
  - 英语学习
  - 翻译
  - 考试
  - 学习
  - 成长
    plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
    exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .vscode/
  - .idea/
  - .DS_Store
  - Thumbs.db 
